insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(90,'Sri Lanka Airlines','SR','AMPARAI');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(30,'Eritrea Airlines','ER','ASMARA INTL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(61,'Lebanon Airlines','LE','BEIRUT INTL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(71,'Nicaragua Airlines','NI','BLUEFIELDS');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(62,'Liberia Airlines','LI','BUCKANAN');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(82,'Russia Airlines','RU','ABAKAN');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(17,'Colombia Airlines','CO','AGUAS CLARAS');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(20,'Cyprus Airlines','CY','AKROTIRI AB');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(45,'Iceland Airlines','IC','AKUREYRI');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(4,'Angola Airlines','AN','ALBANO MACHADO');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(22,'Dakhla And Laayoune ','DA','DAKHLA');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(79,'Qatar Airlines','QA','DOHA INTL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(84,'San Andres Airlines','SA','GUSTAVO ROJAS PINILLA');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(52,'Jerusalem Airlines','JE','JERUSALEM');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(73,'Oman Airlines','OM','KHASAB AB');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(8,'Bahamas Airlines','BA','ANDROS TOWN INTL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(11,'Bolivia Airlines','BO','APOLO');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(103,'Uruguay Airlines','UR','ARTIGAS INTL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(77,'Poland Airlines','PO','BABIMOST');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(41,'Guadeloupe Airlines','GU','BAILLIF');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(85,'Senegal Airlines','SE','BAKEL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(7,'Azerbaijan Airlines','AZ','BINA');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(36,'Gabon Airlines','GA','BITAM');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(101,'Ukraine Airlines','UK','BORYSPIL�');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(32,'Ethiopia Airlines','ET','A.T.D. YILMA INTL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(50,'Ivory Coast Airlines','IV','ABENGOUROU');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(27,'Egypt Airlines','EG','ABU SIMBEL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(12,'Brazil Airlines','BR','AEROCLUB');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(40,'Greece Airlines','GR','AGRINION AB');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(35,'France Airlines','FR','AIX-LES-BAINS');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(49,'Italy Airlines','IT','ALBENGA');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(80,'Reunion Airlines','RE','GILLOT');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(99,'Tunisia Airlines','TU','CARTHAGE');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(34,'Fiji Is Airlines','FI','LABASA');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(53,'Johnston Atoll Airli','JO','JOHNSTON ATOLL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(87,'Slovakia Airlines','SL','KOSICE');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(59,'Kyrgyzstan Airlines','KY','MANAS');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(81,'Romania Airlines','RO','ARAD');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(100,'Uganda Airlines','UG','ARUA');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(44,'Hungary Airlines','HU','BALATON');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(105,'Vanuatu Airlines','VA','BAUERFIELD');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(111,'Yugoslavia Airlines','YU','BELGRADE');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(113,'Zimbabwe Airlines','ZI','BUFFALO RANGE');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(89,'Spain Airlines','SP','A CORUNA');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(110,'Yemen Airlines','YE','ABBS');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(6,'Australia Airlines','AU','ADELAIDE INTL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(55,'Kenya Airlines','KE','AMBOSELI');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(24,'Djibouti Airlines','DJ','AMBOULI');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(31,'Estonia Airlines','ES','KARDLA');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(37,'Georgia Airlines','GE','KOPITNARI');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(63,'Luxembourg Airlines','LU','LUXEMBOURG');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(108,'Wake I Airlines','WA','WAKE I AAF');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(78,'Puerto Rico Airlines','PU','ANTONOV');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(69,'Namibia Airlines','NA','ARANDIS');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(66,'Micronesia Airlines','MI','BABELTHUAP KOROR');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(68,'Myanmar Airlines','MY','BAGAN');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(15,'Central African Rep ','CE','BALANDINO');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(1,'Afghanistan Airlines','AF','BAMYAN');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(96,'Thailand Airlines','TH','BANGKOK INTL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(51,'Jamaica Airlines','JA','BOSCOBEL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(57,'Korea Airlines','KO','A-306');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(16,'Chad Airlines','CH','ABECHE');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(46,'India Airlines','IN','AGARTALA');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(106,'Venezuela Airlines','VE','ALBERTO CARNEVALLI');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(74,'Pakistan Airlines','PA','ALLAMA IQBAL INTL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(39,'Gibraltar Airlines','GI','GIBRALTAR AB');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(43,'Honduras Airlines','HO','CATACAMAS');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(112,'Zambia Airlines','ZA','CHIPATA');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(14,'Caicos Is Airlines','CA','CONCH BAR');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(38,'Ghana Airlines','GH','KOTOKA INTL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(97,'Togo Airlines','TO','NIAMTOUGOU');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(65,'Melilla Airlines','ME','MELILLA');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(33,'Falkland Is Airlines','FA','MOUNT PLEASANT');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(104,'Uzbekistan Airlines','UZ','BUKHARA');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(107,'Vietnam Airlines','VI','BUONMATHUOT');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(13,'Bulgaria Airlines','BU','BURGAS');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(83,'Rwanda Airlines','RW','BUTARE');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(94,'Syria Airlines','SY','ALEPPO INTL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(26,'Ecuador Airlines','EC','CHACHOAN');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(95,'Taiwan Airlines','TA','CHIANG KAI SHEK INTL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(21,'Czech Airlines','CZ','HOLESOV');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(10,'Bhutan Airlines','BH','PARO');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(64,'Macau Airlines','MA','MACAU INTL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(9,'Belarus Airlines','BE','BREST');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(47,'Iran Airlines','IR','ABADAN');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(28,'El Salvador Airlines','EL','EL SALVADOR INTL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(88,'Solomon Is Airlines','SO','GIZO');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(42,'Haiti Airlines','HA','CAP HAITIEN INTL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(91,'St Kitts Airlines','ST','NEWCASTLE');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(3,'American Samoa Airli','AM','PAGO PAGO INTL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(48,'Isla De Pascua Airli','IS','MATAVERI INTL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(92,'Sudan Airlines','SU','ATBARA');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(76,'Philippines Airlines','PH','BACOLOD');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(29,'Equatorial Guinea Ai','EQ','BATA');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(86,'Sierra Leone Airline','SI','BO');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(56,'Kiribati Airlines','KI','BONRIKI INTL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(19,'Cuba Airlines','CU','ABEL SANTA MARIA');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(102,'United Arab Emirates','UN','ABU DHABI INTL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(54,'Kazakhstan Airlines','KA','AKTAU');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(75,'Peru Airlines','PE','ALEJANDRO VELAZCO ASTETE');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(109,'Western Samoa Airlin','WE','FAGALI');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(25,'Dominica Airlines','DO','CANEFIELD INTL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(67,'Moldova Airlines','MO','CHISINAU');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(18,'Croatia Airlines','CR','CILIPI');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(58,'Kuwait Airlines','KU','KUWAIT INTL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(93,'Swaziland Airlines','SW','MATSAPHA INTL');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(60,'Laos Airlines','LA','ATTOPEU');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(70,'Nepal Airlines','NE','BAGLUNG');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(23,'Denmark Airlines','DE','AALBORG');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(5,'Argentina Airlines','AR','ALMIRANTE ZAR');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(98,'Trinidad Airlines','TR','CROWN POINT');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(2,'Albania Airlines','AL','RINAS');
insert into airline.airlines(airline_id,airline_name,iata,base_airport_name) values(72,'Northern Mariana Is ','NO','ROTA I INTL');